export const endpoints = {
  v1: {
    partner_create: "/partner",
    partner_get: "/partner/{partnerId}",
    partner_subdomain: "/partner/subdomain/{subdomain}",
    partner_email: "/partner/email/{email}",
    activity_create: "/activity",
    activity_update: "/activity",
    activity_get: "/activity/{activityId}",
    activity_list: "/activity/partner/{partnerId}",
    activity_upload_image: "/activity/image",
    activity_remove: "/activity/{activityId}",
    event_create: "/event",
    event_list: "/event/activity/{activityId}",
    event_get: "/event/{eventId}",
    event_update: "/event",
    event_remove: "/event/{eventId}",
    booking_event: "/booking/event/{eventId}",
    booking_init: "/booking/init",
    booking_add_guest: "/booking/guest",
    booking_finish: "/booking/finish",
    booking_get: "/booking/{bookingId}",
    booking_list_by_event: "/bookings/event/{eventId}",
    booking_list_with_filter: "/bookings",
    booking_update: "/booking",
    guest_create: "/guest",
    guest_list: "/guest/{partnerId}",
  },
};
